name: Java CI with Maven - Build WAR on HelloServlet Change

on:
  push:
    branches: [feature-duchuy-jv2]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: "21"
          distribution: "temurin"
      - name: Run Unit Tests with Maven
        run: mvn clean test
      - name: Verify with Maven
        run: mvn clean verify # Kiểm tra mã
      - name: Build with Maven
        run: mvn package # Build WAR
      - name: Upload WAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: servlet-war
          path: target/*.war
          if-no-files-found: error